### ISSUE TITLE
Adding an RSS feed

### ISSUE THREAD

**Issue by goranmoomin** [leontrolski/leontrolski.github.io#2]
Hello, I'm a reader of your great blog posts! One thing I have always felt inconvenient was that I don't have any mechanism to get updates unless I frequently check.
Would it be possible to have an RSS feed of the posts? I guess you aren't writing the posts in pure HTML - if it's possible to push the code (whether it's Jekyll or  used for writing the posts, I'm more than eager to help you adding the feed. Thanks!

**Comment by leontrolski** [comment]
Thanks a load! I've been writing the html by hand (as god intended) which hasn't been painful enough for me to learn anything else 😸

I'm not too hot on exactly what I need for RSS support (and can't be bothered to dig any further) will this: https://github.com/leontrolski/leontrolski.github.io/commit/8d02ba2ae4d6e2f414064acecaa118fb229a71ff do it?

**Comment by goranmoomin** [comment]
Oh, thanks for the quick response! Unfortunately, I find the hand written RSS feed a bit bare bones :cry:

If writing HTML by hand is the case, would you mind placing the WIP articles in a dedicated folder? I think I might be able to write a shell script that scrapes the posts and generates a RSS feed automatically with a bit of bells and whistles (like adding the content of the blog post, etc...) when I have my free time... Thanks for your care for this! :heart:

**Comment by leontrolski** [comment]
This is a good idea for my sanity too, will do it now. Out of interest, which information/fields would you also like in the RSS? (a summary? publication date?). I'd be happy to do it if it ain't too much work. 

I'm slightly loth to put the whole post in the RSS stream as I feel the code snippets are important.

**Comment by goranmoomin** [comment]
@leontrolski I opened a PR that adds the script and updates the RSS feed - can you check it out?

(Code snippets gets converted to HTML and get shown in the feed reader.)
